//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QId { get; set; }
        public string Option_A { get; set; }
        public string Option_B { get; set; }
        public string Option_C { get; set; }
        public string Option_D { get; set; }
        public string Answer { get; set; }
        public int Text_ID { get; set; }
        public string Soru { get; set; }
    
        public virtual Text Text { get; set; }
    }
}
